# Generated by Django 5.2.1 on 2025-05-16 20:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0003_alter_customuser_role_student'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('constraints', models.JSONField(blank=True, default=dict, help_text='Stores extracted constraints like marks, CO/BT focus, units.')),
                ('part_a_question_ids', models.JSONField(blank=True, default=list)),
                ('part_b_question_ids', models.JSONField(blank=True, default=list)),
                ('conversation_history', models.JSONField(blank=True, default=list, help_text="List of {'role': 'user/assistant', 'content': '...'}")),
                ('ai_meta_data', models.JSONField(blank=True, default=dict, help_text='Structured data from AI, e.g., suggestions, coverage.')),
                ('status', models.CharField(choices=[('drafting', 'Drafting'), ('review', 'Under Review'), ('finalized', 'Finalized'), ('archived', 'Archived')], default='drafting', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_paper_drafts', to='api.course')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_paper_drafts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
