# Generated by Django 5.2 on 2025-04-08 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_customuser_date_joined_customuser_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("faculty", "Faculty"),
                    ("student", "Student"),
                ],
                default="faculty",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "s_id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("usn", models.CharField(max_length=50)),
                (
                    "user",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Student",
                "indexes": [
                    models.Index(fields=["name"], name="student_name_idx"),
                    models.Index(fields=["email"], name="student_email_idx"),
                ],
            },
        ),
    ]
