# Generated by Django 5.2.1 on 2025-07-05 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_question_answer_answerscheme_questionanswer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviewer',
            fields=[
                ('r_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Reviewer',
                'indexes': [models.Index(fields=['name'], name='reviewer_name_idx'), models.Index(fields=['email'], name='reviewer_email_idx')],
            },
        ),
    ]
