# Generated by Django 5.2.1 on 2025-07-06 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_reviewer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('faculty', 'Faculty'), ('student', 'Student'), ('reviewer', 'Reviewer')], default='faculty', max_length=50),
        ),
    ]
